
#pragma once

#include "NativeGameplayTags.h"

namespace W1GameplayTags
{
	//Input Tags
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);

	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);

	//Player Tags
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);

	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);

	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	//Enemy Tags
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);

	//Shared Tags
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);

	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	W1_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
}